name: onedmin-env

dependencies:
    - python=3.7
    - pybind11
    - numpy
    - pytest
    - pytest-cov
    - future
    - flake8
    - pylint
    - cmake
    - gfortran_linux-64
    - blas
    - openblas # [linux]
